<?php

defined('BASEPATH') or exit('No direct script access allowed');

$CI = & get_instance();

if (!$CI->db->table_exists(db_prefix() . 'receipts')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "receipts` (
        `id` BIGINT(20) UNSIGNED NOT NULL,
        `date` DATE NOT NULL,
        `amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `received_amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `balance` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,

        `client_id` INT(11) DEFAULT NULL,
        `account_id` INT(11) DEFAULT NULL,
        `donor_id` INT(11) DEFAULT NULL,
        `category_id` INT(11) NOT NULL,
        `sub_category_id` INT(11) DEFAULT NULL,
        `sub_sub_category_id` INT(11) DEFAULT NULL,
        `sub_sub_sub_category_id` INT(11) DEFAULT NULL,

        `reference` VARCHAR(255) DEFAULT NULL,
        `description` LONGTEXT DEFAULT NULL,
        `attachment` VARCHAR(255) DEFAULT NULL,

        `is_fully_received` TINYINT(1) NOT NULL DEFAULT 0,
        `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'receipts`
        ADD PRIMARY KEY (`id`),
        ADD KEY `client_id` (`client_id`),
        ADD KEY `account_id` (`account_id`),
        ADD KEY `donor_id` (`donor_id`),
        ADD KEY `category_id` (`category_id`),
        ADD KEY `sub_category_id` (`sub_category_id`),
        ADD KEY `sub_sub_category_id` (`sub_sub_category_id`),
        ADD KEY `sub_sub_sub_category_id` (`sub_sub_sub_category_id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'receipts`
        MODIFY `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

if (!$CI->db->table_exists(db_prefix() . 'categories')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "categories` (
        `id` BIGINT(20) UNSIGNED NOT NULL,
        `name` VARCHAR(255) NOT NULL,
        `type` VARCHAR(255) NOT NULL,
        `parent_id` INT(11) NOT NULL DEFAULT 0,
        `is_default` TINYINT(1) NOT NULL DEFAULT 0,
        `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'categories`
        ADD PRIMARY KEY (`id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'categories`
        MODIFY `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

$categories = [
    [
        'id' => 1,
        'name' => 'Member Contribution',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 2,
        'name' => 'Donation',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 3,
        'name' => 'Grant',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 4,
        'name' => 'Non-current liabilities',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 5,
        'name' => 'Other Income',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 6,
        'name' => 'Program 1',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 7,
        'name' => 'Program 2',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 8,
        'name' => 'Program 3',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 9,
        'name' => 'Employee benefits expense',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 10,
        'name' => 'Rent',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 11,
        'name' => 'Electricity',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 12,
        'name' => 'Travelling expenses',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 13,
        'name' => 'Printing & Stationary',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 14,
        'name' => 'Registration Expenses',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 15,
        'name' => 'Other Expenses',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 16,
        'name' => 'Loan Repayment',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 17,
        'name' => 'Property, Plant and Equipment and Intangible assets',
        'type' => 3,
        'parent_id' => 197,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 18,
        'name' => 'Advance',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 19,
        'name' => 'Freehold land',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 20,
        'name' => 'Buildings',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 21,
        'name' => 'Plant and Equipment',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 22,
        'name' => 'Office equipment',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 23,
        'name' => 'Furniture & Fixtures',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 24,
        'name' => 'Vehicles',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 25,
        'name' => 'Tangible Assets',
        'type' => 3,
        'parent_id' => 17,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 26,
        'name' => 'Others',
        'type' => 3,
        'parent_id' => 25,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 27,
        'name' => 'Unrestricted funds',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 28,
        'name' => 'Corpus',
        'type' => 1,
        'parent_id' => 27,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 29,
        'name' => 'Designated funds',
        'type' => 1,
        'parent_id' => 27,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 30,
        'name' => 'Restricted funds',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 31,
        'name' => 'Fees from Rendering of Services',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 32,
        'name' => 'Sale of Goods',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 33,
        'name' => 'Interest Income',
        'type' => 1,
        'parent_id' => 5,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 34,
        'name' => 'Dividend Income',
        'type' => 1,
        'parent_id' => 5,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 35,
        'name' => 'Net gain on sale of investments',
        'type' => 1,
        'parent_id' => 5,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 36,
        'name' => 'Other non-operating income',
        'type' => 1,
        'parent_id' => 5,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 37,
        'name' => 'Material consumed/distributed',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 38,
        'name' => 'Donations/contributions paid',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 39,
        'name' => 'Finance costs',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 40,
        'name' => 'Interest expense on bank loan',
        'type' => 2,
        'parent_id' => 39,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 41,
        'name' => 'Interest Income on assets on finance lease',
        'type' => 2,
        'parent_id' => 39,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 42,
        'name' => 'Other borrowing costs',
        'type' => 2,
        'parent_id' => 39,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 43,
        'name' => 'Bank Charges',
        'type' => 2,
        'parent_id' => 39,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 44,
        'name' => 'Consumption of stores and parts',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 45,
        'name' => 'Power and fuel',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 46,
        'name' => 'Repairs and maintenance - Buildings',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 47,
        'name' => 'Repairs and maintenance - Machinery',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 48,
        'name' => 'Insurance',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 49,
        'name' => 'Rent, Rates and taxes, excluding, taxes on income',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 50,
        'name' => 'Labour charges',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 51,
        'name' => 'Auditors remuneration',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 52,
        'name' => 'Communication expenses',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 53,
        'name' => 'Legal and professional charges',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 54,
        'name' => 'Advertisement and publicity',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 55,
        'name' => 'Business promotion expenses',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 56,
        'name' => 'Commission',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 57,
        'name' => 'Clearing and forwarding charges',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 58,
        'name' => 'Miscellaneous expenses',
        'type' => 2,
        'parent_id' => 15,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 59,
        'name' => 'Religious/charitable',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 60,
        'name' => 'Long-term borrowings',
        'type' => 1,
        'parent_id' => 4,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 61,
        'name' => 'Other long-term liabilities',
        'type' => 1,
        'parent_id' => 4,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 62,
        'name' => 'Long-term provisions',
        'type' => 1,
        'parent_id' => 4,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 63,
        'name' => 'Current liabilities',
        'type' => 1,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 64,
        'name' => 'Short-term borrowings',
        'type' => 1,
        'parent_id' => 63,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 65,
        'name' => 'Other-current liabilities',
        'type' => 1,
        'parent_id' => 63,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 66,
        'name' => 'Short-term provisions',
        'type' => 1,
        'parent_id' => 63,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 67,
        'name' => 'Secured',
        'type' => 1,
        'parent_id' => 60,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 68,
        'name' => 'Unsecured',
        'type' => 1,
        'parent_id' => 60,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 69,
        'name' => 'Term loans from banks',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 70,
        'name' => 'Term loans from other parties',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 71,
        'name' => 'Loans repayable on demand from banks',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 72,
        'name' => 'Loans repayable on demand from other parties',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 73,
        'name' => 'Deferred payment liabilities',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 74,
        'name' => 'Loans and advances from related parties',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 75,
        'name' => 'Long term/current maturities of finance lease obligation',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 76,
        'name' => 'Other loans advances',
        'type' => 1,
        'parent_id' => 67,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 77,
        'name' => 'Term loans from banks',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 78,
        'name' => 'Term loans from other parties',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 79,
        'name' => 'Loans repayable on demand from banks',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 80,
        'name' => 'Loans repayable on demand from other parties',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 81,
        'name' => 'Deferred payment liabilities',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 82,
        'name' => 'Loans and advances from related parties',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 83,
        'name' => 'Long term/current maturities of finance lease obligation',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 84,
        'name' => 'Other loans advances',
        'type' => 1,
        'parent_id' => 68,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 85,
        'name' => 'Advance from customers',
        'type' => 1,
        'parent_id' => 61,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 86,
        'name' => 'Secured',
        'type' => 1,
        'parent_id' => 64,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 87,
        'name' => 'Unsecured',
        'type' => 1,
        'parent_id' => 64,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 88,
        'name' => 'Term loans from banks',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 89,
        'name' => 'Term loans from other parties',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 90,
        'name' => 'Loans repayable on demand from banks',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 91,
        'name' => 'Loans repayable on demand from other parties',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 92,
        'name' => 'Deferred payment liabilities',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 93,
        'name' => 'Loans and advances from related parties',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 94,
        'name' => 'Long term/current maturities of finance lease obligation',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 95,
        'name' => 'Other loans advances',
        'type' => 1,
        'parent_id' => 86,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 96,
        'name' => 'Term loans from banks',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 97,
        'name' => 'Term loans from other parties',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 98,
        'name' => 'Loans repayable on demand from banks',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 99,
        'name' => 'Loans repayable on demand from other parties',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 100,
        'name' => 'Deferred payment liabilities',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 101,
        'name' => 'Loans and advances from related parties',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 102,
        'name' => 'Long term/current maturities of finance lease obligation',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 103,
        'name' => 'Other loans advances',
        'type' => 1,
        'parent_id' => 87,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 104,
        'name' => 'Current maturities of finance lease obligations',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 105,
        'name' => 'Interest accrued but not due on borrowings',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 106,
        'name' => 'Interest accrued and due on borrowings',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 107,
        'name' => 'Income received in advance',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 108,
        'name' => 'Unearned revenue',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 109,
        'name' => 'Goods and Service tax payable',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 110,
        'name' => 'TDS payable',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 111,
        'name' => 'Other payables',
        'type' => 1,
        'parent_id' => 65,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 112,
        'name' => 'Provision for employee benefits',
        'type' => 1,
        'parent_id' => 62,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 113,
        'name' => 'Other provisions',
        'type' => 1,
        'parent_id' => 62,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 114,
        'name' => 'Provision for employee benefits',
        'type' => 1,
        'parent_id' => 66,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 115,
        'name' => 'Other provisions',
        'type' => 1,
        'parent_id' => 66,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 116,
        'name' => 'Non-current investments',
        'type' => 3,
        'parent_id' => 197,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 117,
        'name' => 'Trade Investments-Quoted',
        'type' => 3,
        'parent_id' => 116,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 118,
        'name' => 'Trade Investments-Unquoted',
        'type' => 3,
        'parent_id' => 116,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 119,
        'name' => 'Other Investments',
        'type' => 3,
        'parent_id' => 116,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 120,
        'name' => 'Long Term Loans and Advances',
        'type' => 3,
        'parent_id' => 197,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 121,
        'name' => 'Secured',
        'type' => 3,
        'parent_id' => 120,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 122,
        'name' => 'Unsecured',
        'type' => 3,
        'parent_id' => 120,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 123,
        'name' => 'Capital advances',
        'type' => 3,
        'parent_id' => 121,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 124,
        'name' => 'Considered good',
        'type' => 3,
        'parent_id' => 123,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 125,
        'name' => 'Doubtful',
        'type' => 3,
        'parent_id' => 123,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 126,
        'name' => 'Loans advances to partners or relative of partners',
        'type' => 3,
        'parent_id' => 121,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 127,
        'name' => 'Other loans and advances',
        'type' => 3,
        'parent_id' => 121,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 128,
        'name' => 'Prepaid expenses',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 129,
        'name' => 'CENVAT credit receivable',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 130,
        'name' => 'VAT credit receivable',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 131,
        'name' => 'Service tax credit receivable',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 132,
        'name' => 'GST input credit receivable',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 133,
        'name' => 'Security Deposits',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 134,
        'name' => 'Balance with government authorities',
        'type' => 3,
        'parent_id' => 127,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 135,
        'name' => 'Capital advances',
        'type' => 3,
        'parent_id' => 122,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 136,
        'name' => 'Considered good',
        'type' => 3,
        'parent_id' => 135,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 137,
        'name' => 'Doubtful',
        'type' => 3,
        'parent_id' => 135,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 138,
        'name' => 'Loans advances to partners or relative of partners',
        'type' => 3,
        'parent_id' => 122,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 139,
        'name' => 'Other loans and advances',
        'type' => 3,
        'parent_id' => 122,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 140,
        'name' => 'Prepaid expenses',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 141,
        'name' => 'CENVAT credit receivable',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 142,
        'name' => 'VAT credit receivable',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 143,
        'name' => 'Service tax credit receivable',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 144,
        'name' => 'GST input credit receivable',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 145,
        'name' => 'Security Deposits',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 146,
        'name' => 'Balance with government authorities',
        'type' => 3,
        'parent_id' => 139,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 147,
        'name' => 'Other non-current assets',
        'type' => 3,
        'parent_id' => 197,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 148,
        'name' => 'Security Deposits',
        'type' => 3,
        'parent_id' => 147,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 149,
        'name' => 'Prepaid expenses',
        'type' => 3,
        'parent_id' => 147,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 150,
        'name' => 'Current investments',
        'type' => 3,
        'parent_id' => 198,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 151,
        'name' => 'Trade Investments-Quoted',
        'type' => 3,
        'parent_id' => 150,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 152,
        'name' => 'Trade Investments-Unquoted',
        'type' => 3,
        'parent_id' => 150,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 153,
        'name' => 'Other Investments',
        'type' => 3,
        'parent_id' => 150,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 154,
        'name' => 'Short Term Loans and Advances',
        'type' => 3,
        'parent_id' => 198,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 155,
        'name' => 'Secured',
        'type' => 3,
        'parent_id' => 154,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 156,
        'name' => 'Unsecured',
        'type' => 3,
        'parent_id' => 154,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 157,
        'name' => 'Capital advances',
        'type' => 3,
        'parent_id' => 155,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 158,
        'name' => 'Considered good',
        'type' => 3,
        'parent_id' => 157,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 159,
        'name' => 'Doubtful',
        'type' => 3,
        'parent_id' => 157,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 160,
        'name' => 'Loans advances to partners or relative of partners',
        'type' => 3,
        'parent_id' => 155,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 161,
        'name' => 'Other loans and advances',
        'type' => 3,
        'parent_id' => 155,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 162,
        'name' => 'Prepaid expenses',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 163,
        'name' => 'CENVAT credit receivable',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 164,
        'name' => 'VAT credit receivable',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 165,
        'name' => 'Service tax credit receivable',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 166,
        'name' => 'GST input credit receivable',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 167,
        'name' => 'Security Deposits',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 168,
        'name' => 'Balance with government authorities',
        'type' => 3,
        'parent_id' => 161,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 169,
        'name' => 'Capital advances',
        'type' => 3,
        'parent_id' => 156,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 170,
        'name' => 'Considered good',
        'type' => 3,
        'parent_id' => 169,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 171,
        'name' => 'Doubtful',
        'type' => 3,
        'parent_id' => 169,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 172,
        'name' => 'Loans advances to partners or relative of partners',
        'type' => 3,
        'parent_id' => 156,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 173,
        'name' => 'Other loans and advances',
        'type' => 3,
        'parent_id' => 156,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 174,
        'name' => 'Prepaid expenses',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 175,
        'name' => 'CENVAT credit receivable',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 176,
        'name' => 'VAT credit receivable',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 177,
        'name' => 'Service tax credit receivable',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 178,
        'name' => 'GST input credit receivable',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 179,
        'name' => 'Security Deposits',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 180,
        'name' => 'Balance with government authorities',
        'type' => 3,
        'parent_id' => 173,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 181,
        'name' => 'Other current assets',
        'type' => 3,
        'parent_id' => 198,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 182,
        'name' => 'Interest accrued but not due on deposits',
        'type' => 3,
        'parent_id' => 181,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 183,
        'name' => 'Interest accrued and due on deposits',
        'type' => 3,
        'parent_id' => 181,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 184,
        'name' => 'Cash and Bank Balances',
        'type' => 3,
        'parent_id' => 198,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 185,
        'name' => 'Cash and cash equivalents',
        'type' => 3,
        'parent_id' => 184,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 186,
        'name' => 'Other bank balances',
        'type' => 3,
        'parent_id' => 184,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 187,
        'name' => 'On current accounts',
        'type' => 3,
        'parent_id' => 185,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 188,
        'name' => 'Cash credit account',
        'type' => 3,
        'parent_id' => 185,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 189,
        'name' => 'Fixed Deposits',
        'type' => 3,
        'parent_id' => 185,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 190,
        'name' => 'Cheques, drafts on hand',
        'type' => 3,
        'parent_id' => 185,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 191,
        'name' => 'Cash on hand',
        'type' => 3,
        'parent_id' => 185,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 192,
        'name' => 'Bank deposits',
        'type' => 3,
        'parent_id' => 186,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 193,
        'name' => 'Earmarked Bank Deposits',
        'type' => 3,
        'parent_id' => 192,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 194,
        'name' => 'Deposits with original maturity for more than 3 months but less than 12 months from reporting date',
        'type' => 3,
        'parent_id' => 192,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 195,
        'name' => 'Margin money or deposits under lien',
        'type' => 3,
        'parent_id' => 192,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 196,
        'name' => 'Others',
        'type' => 3,
        'parent_id' => 192,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 197,
        'name' => 'Non-current assets',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 198,
        'name' => 'Current assets',
        'type' => 2,
        'parent_id' => 0,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 199,
        'name' => 'Intangible Assets',
        'type' => 3,
        'parent_id' => 17,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 200,
        'name' => 'Goodwill',
        'type' => 3,
        'parent_id' => 199,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 201,
        'name' => 'Computer Software',
        'type' => 3,
        'parent_id' => 199,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 202,
        'name' => 'Copyrights/patents',
        'type' => 3,
        'parent_id' => 199,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 203,
        'name' => 'Liscense and franchise',
        'type' => 3,
        'parent_id' => 199,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
    [
        'id' => 204,
        'name' => 'Others',
        'type' => 3,
        'parent_id' => 199,
        'is_default' => 1,
        'datecreated' => date('Y-m-d H:i:s'),
    ],
];

$CI->db->insert_batch(db_prefix() . 'categories', $categories);

if (!$CI->db->table_exists(db_prefix() . 'bank_accounts')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "bank_accounts` (
        `id` BIGINT(20) UNSIGNED NOT NULL,
        `holder_name` VARCHAR(255) NOT NULL,
        `bank_name` VARCHAR(255) NOT NULL,
        `bank_type` VARCHAR(255) NOT NULL,
        `account_number` VARCHAR(255) NOT NULL,
        `opening_balance` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `bank_address` VARCHAR(255) NOT NULL,
        `contact_number` VARCHAR(255) NOT NULL,
        `bank_branch` VARCHAR(255) NOT NULL,
        `client_id` INT(11) DEFAULT NULL,
        `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'bank_accounts`
        ADD PRIMARY KEY (`id`),
        ADD KEY `client_id` (`client_id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'bank_accounts`
        MODIFY `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

if (!$CI->db->table_exists(db_prefix() . 'payments')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "payments` (
        `id` BIGINT(20) UNSIGNED NOT NULL,
        `date` DATE NOT NULL,
        `amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `received_amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `balance` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,

        `client_id` INT(11) DEFAULT NULL,
        `account_id` INT(11) DEFAULT NULL,
        `vendorid` INT(11) DEFAULT NULL,
        `description` LONGTEXT DEFAULT NULL,

        `category_id` INT(11) DEFAULT NULL,
        `sub_category_id` INT(11) DEFAULT NULL,
        `sub_sub_category_id` INT(11) DEFAULT NULL,
        `sub_sub_sub_category_id` INT(11) DEFAULT NULL,
        `receipt_category_id` INT(11) DEFAULT NULL,
        `asset_category_id` INT(11) DEFAULT NULL,
        `receipt_id` INT(11) DEFAULT NULL,

        `reference` VARCHAR(255) DEFAULT NULL,
        `attachment` VARCHAR(255) DEFAULT NULL,

        `is_fully_paid` TINYINT(1) NOT NULL DEFAULT 0,
        `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'payments`
        ADD PRIMARY KEY (`id`),
        ADD KEY `client_id` (`client_id`),
        ADD KEY `account_id` (`account_id`),
        ADD KEY `vendorid` (`vendorid`),
        ADD KEY `category_id` (`category_id`),
        ADD KEY `sub_category_id` (`sub_category_id`),
        ADD KEY `sub_sub_category_id` (`sub_sub_category_id`),
        ADD KEY `sub_sub_sub_category_id` (`sub_sub_sub_category_id`),
        ADD KEY `receipt_category_id` (`receipt_category_id`),
        ADD KEY `asset_category_id` (`asset_category_id`),
        ADD KEY `receipt_id` (`receipt_id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'payments`
        MODIFY `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

if (!$CI->db->table_exists(db_prefix() . 'transaction')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "transaction` (
        `id` BIGINT(20) UNSIGNED NOT NULL,
        `client_id` INT(11) DEFAULT NULL,
        `account_id` INT(11) DEFAULT NULL,
        `type` INT(11) DEFAULT NULL,

        `amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `received_amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `total_balance` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,

        `description` LONGTEXT DEFAULT NULL,
        `date` DATE NOT NULL,
        `track_id` INT(11) DEFAULT NULL,

        `category` VARCHAR(255) DEFAULT NULL,
        `sub_category` VARCHAR(255) DEFAULT NULL,
        `sub_sub_category` VARCHAR(255) DEFAULT NULL,
        `sub_sub_sub_category` VARCHAR(255) DEFAULT NULL,
        `receipt_category` VARCHAR(255) DEFAULT NULL,
        `asset_category` VARCHAR(255) DEFAULT NULL,

        `previous_balance` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `balance` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,

        `is_fully_paid_or_received` TINYINT(1) NOT NULL DEFAULT 0,
        `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'transaction`
        ADD PRIMARY KEY (`id`),
        ADD KEY `client_id` (`client_id`),
        ADD KEY `account_id` (`account_id`),
        ADD KEY `track_id` (`track_id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'transaction`
        MODIFY `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

if (!$CI->db->table_exists(db_prefix() . 'asset_depreciation')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "asset_depreciation` (
        `id` BIGINT(20) UNSIGNED NOT NULL,
        `client_id` INT(11) DEFAULT NULL,
        `category` VARCHAR(255) NOT NULL,
        `month_year` VARCHAR(7) NOT NULL,
        `amount` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
        `rate` INT(11) DEFAULT 0,
        `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'asset_depreciation`
        ADD PRIMARY KEY (`id`),
        ADD UNIQUE KEY `asset_depreciation_category_month_year_unique` (`category`,`month_year`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'asset_depreciation`
        MODIFY `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

if (!$CI->db->table_exists(db_prefix() . 'donors')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "donors` (
        `donorid` BIGINT(20) UNSIGNED NOT NULL,
        `name` VARCHAR(255) NOT NULL,
        `email` VARCHAR(255) DEFAULT NULL,
    `phonenumber` VARCHAR(50) DEFAULT NULL,
    `address` TEXT DEFAULT NULL,
    `gst_number` VARCHAR(100) DEFAULT NULL,
    `notes` TEXT DEFAULT NULL,
    `balance` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    `client_id` INT(11) DEFAULT NULL,
    `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'donors`
        ADD PRIMARY KEY (`donorid`),
        ADD KEY `client_id` (`client_id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'donors`
        MODIFY `donorid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}

if (!$CI->db->table_exists(db_prefix() . 'vendors')) {

    $CI->db->query('CREATE TABLE `' . db_prefix() . "vendors` (
        `vendorid` BIGINT(20) UNSIGNED NOT NULL,
        `name` VARCHAR(255) NOT NULL,
        `email` VARCHAR(255) DEFAULT NULL,
    `phonenumber` VARCHAR(50) DEFAULT NULL,
    `address` TEXT DEFAULT NULL,
    `gst_number` VARCHAR(100) DEFAULT NULL,
    `notes` TEXT DEFAULT NULL,
    `balance` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    `client_id` INT(11) DEFAULT NULL,
    `datecreated` DATETIME NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'vendors`
        ADD PRIMARY KEY (`vendorid`),
        ADD KEY `client_id` (`client_id`);
    ');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'vendors`
        MODIFY `vendorid` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
    ');
}