name: Auto commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync to ngo_trust
        run: rsync -av --delete ngo_trust_version_3/ ngo_trust/

      - name: Sync to Version 2
        run: rsync -av --delete ngo_trust_version_3/ ngo_trust_version_2/

      - name: Commit Changes
        run: |
          git config user.name "SuriyaPP"
          git config user.email "duraisuriya9310@gmail.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto sync from ngo_trust_version_3"
            git push origin HEAD:main
          fi